### PR TITLE
Add GitHub Actions and add Black

### LINKED ISSUE #37: Use black (formatter) to check codestyle
Waiting on #38

### LINKED ISSUE #38: Switch to GitHub Actions
Seems good enough now and saves an additional account.

See #21 for the azure version.

### LINKED ISSUE #39: Improve release versioning & pypi deploys
The current tagged commit system is slightly painful, as if the tags and commits aren't pushed at the same time it sometimes messed up and won't do a deploy.[1]

It would probably be beneficial to have a static version file containing the release version which gets used.

I'm not 100% sure on how we'd get the CI to automatically deploy to pypi [does it need to?] when it changes.

[1] I think, I haven't tested this extensively?
Does GitHub actions support this better?

### PR DESCRIPTION
**Pull request by ItayZiv**
Should resolve #37, resolve #38, resolve #39.

### CODE REVIEW

**Comment by ItayZiv** [comment]
Can also be adapted to run on a github release.

**Comment by Modelmat** [comment]
I think it might be a good idea to make it only push to pypi on a github release. That gives a nice confirmation before it gets pushed (and also means tags are descriptory as opposed to being used to actual releasing the library).

Also, I'm assuming I'll have to add my pypi token somewhere, yeah?

**Comment by brechtm** [comment]
Please consider testing on Windows and MacOS as well.

**Comment by Modelmat** [comment]
1. The current GitHub Actions setup seems to fail - https://github.com/ItayZiv/sphinxcontrib-drawio/actions/runs/270312332 . Both the code needs to be formatted w/black first and it appears that git does not seem to work. (see below)
2. I'd much rather it only pushes to PyPI with a repository "release", although that still requires you to tag a commit.

**Comment by Modelmat** [comment]
@ItayZiv Could you fix the build errors?

@brechtm Since you're mostly maintaining this repository now, is there a preferred workflow you like for releases? Is the current way in this PR fine, or would you prefer a different method?

**Comment by brechtm** [comment]
> @brechtm Since you're mostly maintaining this repository now, is there a preferred workflow you like for releases? Is the current way in this PR fine, or would you prefer a different method?

I'm fine with how it works right now on CircleCI, by pushing a tag. if that can be maintained, that's great.

**Comment by ItayZiv** [comment]
Should be ready now.

**Comment by Modelmat** [comment]
@brechtm Could you approve this if you think it's okay?

**Comment by brechtm** [comment]
Looks good to me!

**Review by brechtm — APPROVED** [review]

**Pull request merged**
