### PR TITLE
add '--layer-selection'

### LINKED ISSUE #97: add support for "--layers"
**Is your feature request related to a problem? Please describe.**
I would like to export certain layers to an SVG.
draw.io supports layers, and draw.io CLI allows to specify the layers that shall be exported.

**Describe the solution you'd like**
_sphinxcontrib-drawio_ should allow to specify the layers that shall be exported, and pass this to draw.io CLI.
It should be similar to `--page-index` but as a comma separated list.
If the parameter is not specified then it shall not be passed to draw.io in order to export all _visible_ layers (default behavior).

**Describe alternatives you've considered**
At the moment I export the SVG manually from draw.io, with the desired layers manually made visible.
It does not work well if multiple exports with different layers of the same file are needed.

**Additional context**
Layer selection in CLI has been added in draw.io v20.6.0.

draw.io counts the layers from 0 where layer 0 is the one at the bottom of the list, usually the _Background_ layer.

draw.io CLI:
```
-l, --layers <comma separated layer indexes>
selects which layers to export (applies to all pages), if not specified, all layers are selected
```

### PR DESCRIPTION
**Pull request by MaGeisUMT**
Fixes #97

### CODE REVIEW

**Comment by modelmat** [comment]
Yeah, I wouldn't mind a test if you could. Had issues before where draw.io changes its behaviour on us, so would rather be able to catch that.

**Comment by MaGeisUMT** [comment]
Alright, I will look into how to construct a test case.
Will take few days.

**Comment by stan23** [comment]
Hi @modelmat,
I added positive and negative test cases. They were passing locally.
Is there a way to trigger them in this PR?

**Comment by MaGeisUMT** [comment]
Hi @modelmat,
I added positive and negative test cases, they were passing locally.
Is there a way to execute them within this PR?

**Comment by MaGeisUMT** [comment]
Hi @modelmat, hi @jdillard,
apologies for tagging you. 
Is there anything needed from my side to get this PR picked up?

**Comment by modelmat** [comment]
Sorry for being very nonresponsive. Looks fine I think. If you want to push a release I've given you contributor permissions and I think it just requires pushing a tag for github to autotrigger. It's been too long for me to remember.

**Comment by MaGeisUMT** [comment]
Thanks for the invitation to contributors.

Looks like this time I was unresponsive and the invitation expired.

**Pull request merged**
