### PR TITLE
Implement conversion as post-transform (fixes #52 and #55)

### PR DESCRIPTION
**Pull request by brechtm**
- ImageConverter.handle() was overridden so that diagrams can be
  exported to a subdirectory named after the SHA key and caching remains
  intact.
- Support for `drawio_builder_export_format` was dropped since
  ImageConverter automatically choses the destination format based on
  the builder's supported image types.
- Forcing the export format is handled by having guess_mimetype() return
  a custom MIME type.

### CODE REVIEW

**Comment by prozessorkern** [comment]
Looks like the most elegant solution and should fix the caching problem as well as the need for an output directory.

To be honest I did not understand the implementation to the last detail right now.
These questions came to my mind though:

1. You are overwriting ``handle()`` instead of overwriting ``convert()`` as suggested by the [sphinx documentation](https://www.sphinx-doc.org/en/master/extdev/utils.html?highlight=ImageConverter#sphinx.transforms.post_transforms.images.ImageConverter) - is there a reason for that. And is ensured that ``convert()`` is not called from somewhere esle - otherwise we will end up throwing ``NotImplementedError``
2. Do we lose the possibility of forcing the default output format completely? As now Sphinx decides which format we shall provide is there a possibility to tell sphinx which image format per builder is preferred? I usually prefer SVG or PDF wherever possible - this would be cumbersome to enforce on each and every directive and will not work if the same sourcecode shall be built to HTML and LATEX for example.

**Comment by Modelmat** [comment]
re: default output format
I believe that this becomes the case.
It should be possible to modify the ImageConverter such that the `conversion_rules` can be defined from a config option (this would become a tuple-pair list instead of the previous string option, though). Could most likely to done something like pseudocode:
```py
Converter class:
	conversion_rules = [
		("a", "b"),
	]
	__init__ function
		super().__init__()
		if (conversion_rules):
			self.conversion_rules = self.<something>.config.drawio_conversion_rules 
```

**Comment by brechtm** [comment]
>     1. You are overwriting `handle()` instead of overwriting `convert()` as suggested by the [sphinx documentation](https://www.sphinx-doc.org/en/master/extdev/utils.html?highlight=ImageConverter#sphinx.transforms.post_transforms.images.ImageConverter) - is there a reason for that. And is ensured that `convert()` is not called from somewhere else - otherwise we will end up throwing `NotImplementedError`

Unfortunately, the documented API didn't allow for the hash-based directories we were using to support caching images exported from the same diagram but with different export options. Therefore, I had to override _handle()_ instead of _convert()_. I considered solving this in another way, but that approach required storing state (the diagram currently being processed) to be stored in the _DrawIOConverter_ instance. I decided that this was actually worse than overriding _handle()_.

We could open a PR with Sphinx to make the _ImageConverter_ class more flexible to allow handling our use case, but I'd rather not go through that trouble to be honest. We can simply fix things when Sphinx introduces changes that breaks this, if ever. At that point, we can still consider suggesting a change to the _ImageConverter_ API.

> Do we lose the possibility of forcing the default output format completely? As now Sphinx decides which format we shall provide is there a possibility to tell sphinx which image format per builder is preferred? I usually prefer SVG or PDF wherever possible - this would be cumbersome to enforce on each and every directive and will not work if the same sourcecode shall be built to HTML and LATEX for example.

_ImageConverter_ chooses the preferred format, as encoded in order of items in the _supported_image_types_ member of each Sphinx builder class. For HTML, this is SVG, for LaTeX and rinoh this is PDF, so these align with your preferences.

That said, I had my doubts removing this. I've updated the PR to restore the configuration variable.

**Comment by brechtm** [comment]
Is it OK to merge this? I'd rather not merge #52 first since that PR is obsoleted by this one and will create merge conflicts. It would be good to cherry-pick some of the documentation additions of #52 though.

**Comment by Modelmat** [comment]
> Is it OK to merge this? I'd rather not merge #52 first since that PR is obsoleted by this one and will create merge conflicts. It would be good to cherry-pick some of the documentation additions of #52 though.

I don't see any issues with this in its current state so yes, it is fine to merge.

**Comment by prozessorkern** [comment]
> Is it OK to merge this? I'd rather not merge #52 first since that PR is obsoleted by this one and will create merge conflicts. It would be good to cherry-pick some of the documentation additions of #52 though.

This works for me. So I do not see any benefit of merging #52.
Feel free to copy the documentation additions from #52 I do not have much time right now :(

**Pull request merged**
